/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import clases.ConexionBD;
import clases.repositorios.TipoAlquilerRepositorio;
import clases.repositorios.UsuarioRepositorio;
import clases.repositorios.ViviendaRepositorio;
import java.awt.Color;
import java.sql.SQLException;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.Usuario;
import models.Vivienda;

/**
 *
 * @author j-aco
 */
public class AgregarUsuario extends javax.swing.JFrame {
    
    String idSelected;
    /**
     * Creates new form AgregarUsuario
     */
    public AgregarUsuario() {
        initComponents();
        mostrarUsuarios();
    }
    
    public void mostrarUsuarios(){
            
        try {
            UsuarioRepositorio usuarioRepo = new UsuarioRepositorio();
            List<Usuario> usuario = usuarioRepo.List();
            DefaultTableModel DFT = (DefaultTableModel) tblUsuario.getModel();
            DFT.setRowCount(0);
                for(Usuario u:usuario){
                    Vector v = new Vector();
                    for (int ii = 1; ii <= usuario.size(); ii++) {
                        v.add(u.id_usuario);
                        v.add(u.usuario);
                        v.add(u.nombres);
                        v.add(u.apellidos);
                        v.add(u.telefono);
                        v.add(u.correo);
                        v.add(u.rol);
                    }
                DFT.addRow(v);
                }
            } catch (Exception e) {
                System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        inputUsuario = new javax.swing.JTextField();
        inputContrasenia = new javax.swing.JTextField();
        inputNombres = new javax.swing.JTextField();
        inputApellidos = new javax.swing.JTextField();
        inputTelefono = new javax.swing.JTextField();
        inputCorreo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsuario = new javax.swing.JTable();
        inputRol = new javax.swing.JComboBox<>();
        btnSave = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Agregar Usuario");

        jLabel2.setText("Usuario");

        jLabel3.setText("Contraseña");

        jLabel4.setText("Nombres");

        jLabel5.setText("Apellidos");

        jLabel6.setText("Correo");

        jLabel7.setText("Teléfono");

        jLabel8.setText("Rol");

        inputUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputUsuarioActionPerformed(evt);
            }
        });

        tblUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Id Usuario", "Usuario", "Nombres", "Apellidos", "Telefono", "Correo", "Rol"
            }
        ));
        tblUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblUsuarioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblUsuario);

        inputRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ADMIN", "COUNTER" }));

        btnSave.setText("Guardar");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnClear.setText("Limpiar");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnUpdate.setText("Actualizar");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setText("Eliminar");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(btnSave)
                                .addGap(65, 65, 65)
                                .addComponent(btnClear)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnUpdate)
                                .addGap(54, 54, 54)
                                .addComponent(btnDelete))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(inputTelefono, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(inputNombres, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(inputUsuario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(inputContrasenia, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(inputApellidos, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(inputCorreo)
                                    .addComponent(inputRol, 0, 208, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(62, 62, 62))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(inputUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(inputContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(inputNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inputApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(inputTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(inputCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(inputRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnClear)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputUsuarioActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        ConexionBD con = new ConexionBD();
        String usuario = inputUsuario.getText();
        String contrasenia = inputContrasenia.getText();
        String nombres = inputNombres.getText();
        String apellidos = inputApellidos.getText();
        String telefono = inputTelefono.getText();
        String correo = inputCorreo.getText();
        String rol = inputRol.getSelectedItem().toString();
        
        inputUsuario.setBackground(Color.WHITE);
        inputContrasenia.setBackground(Color.WHITE);
        inputNombres.setBackground(Color.WHITE);
        inputApellidos.setBackground(Color.WHITE);
        inputTelefono.setBackground(Color.WHITE);
        inputCorreo.setBackground(Color.WHITE);
        
        if (usuario.isEmpty() || contrasenia.isEmpty() || apellidos.isEmpty() || telefono.isEmpty() || correo.isEmpty()){
            
            if(usuario.isEmpty()){
                inputUsuario.setBackground(new Color(255,153,153));
            }
            if(contrasenia.isEmpty()){
                inputContrasenia.setBackground(new Color(255,153,153));
            }
            if(nombres.isEmpty()){
                inputNombres.setBackground(new Color(255,153,153));
            }
            if(apellidos.isEmpty()){
                inputApellidos.setBackground(new Color(255,153,153));
            }
            if(telefono.isEmpty()){
                inputTelefono.setBackground(new Color(255,153,153));
            }
            if(correo.isEmpty()){
                inputCorreo.setBackground(new Color(255,153,153));
            }
        }else{
            
            UsuarioRepositorio usuarioRepo = new UsuarioRepositorio();

            Usuario usuarioToSave = new Usuario();
            usuarioToSave.usuario = usuario;
            usuarioToSave.contrasenia = contrasenia;
            usuarioToSave.nombres = nombres;
            usuarioToSave.apellidos = apellidos;
            usuarioToSave.telefono = telefono;
            usuarioToSave.correo = correo;
            usuarioToSave.rol = rol;
            

            try {
                usuarioRepo.crearUsuario(usuarioToSave);
                JOptionPane.showMessageDialog(null, "Se guardo exitosamente");
                mostrarUsuarios();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "No se pudo guardar, intentelo de nuevo");
            }
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int row = tblUsuario.getSelectedRow();
        if(row == -1){
            JOptionPane.showMessageDialog(null, "Debe seleccionar un elemento de la tabla para eliminar");
        }
        else{
            try {
                UsuarioRepositorio usuarioRepo = new UsuarioRepositorio();
                boolean delete = usuarioRepo.eliminarUsuario(Integer.parseInt(idSelected));
                if(delete){
                    inputUsuario.setText("");;
                    inputContrasenia.setText("");;
                    inputNombres.setText("");;
                    inputApellidos.setText("");;
                    inputTelefono.setText("");;
                    inputCorreo.setText("");;
                    idSelected = null;
                    btnUpdate.setEnabled(false);
                    btnSave.setEnabled(true);
                    JOptionPane.showMessageDialog(null, "Se elimino exitosamente");
                    mostrarUsuarios();
                }
                else{
                    JOptionPane.showMessageDialog(null, "No se pudo eliminar, intentelo de nuevo");
                }
                
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "No se pudo eliminar, intentelo de nuevo");
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        inputUsuario.setText("");
        inputContrasenia.setText("");
        inputNombres.setText("");
        inputApellidos.setText("");
        inputContrasenia.setText("");
        inputTelefono.setText("");
        inputCorreo.setText("");
        mostrarUsuarios();
        btnUpdate.setEnabled(false);
        btnSave.setEnabled(true);
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        String usuario = inputUsuario.getText();
        String contrasenia = inputContrasenia.getText();
        String nombres = inputNombres.getText();
        String apellidos = inputApellidos.getText();
        String telefono = inputTelefono.getText();
        String correo = inputCorreo.getText();
        String rol = inputRol.getSelectedItem().toString();
        
        inputUsuario.setBackground(Color.WHITE);
        inputContrasenia.setBackground(Color.WHITE);
        inputNombres.setBackground(Color.WHITE);
        inputApellidos.setBackground(Color.WHITE);
        inputTelefono.setBackground(Color.WHITE);
        inputCorreo.setBackground(Color.WHITE);
        
        if (usuario.isEmpty() || contrasenia.isEmpty() || apellidos.isEmpty() || telefono.isEmpty() || correo.isEmpty()){
            
            if(usuario.isEmpty()){
                inputUsuario.setBackground(new Color(255,153,153));
            }
            if(contrasenia.isEmpty()){
                inputContrasenia.setBackground(new Color(255,153,153));
            }
            if(nombres.isEmpty()){
                inputNombres.setBackground(new Color(255,153,153));
            }
            if(apellidos.isEmpty()){
                inputApellidos.setBackground(new Color(255,153,153));
            }
            if(telefono.isEmpty()){
                inputTelefono.setBackground(new Color(255,153,153));
            }
            if(correo.isEmpty()){
                inputCorreo.setBackground(new Color(255,153,153));
            }
        }else{
            
            UsuarioRepositorio usuarioRepo = new UsuarioRepositorio();

            Usuario usuarioToSave = new Usuario();
            usuarioToSave.id_usuario = Integer.parseInt(idSelected);
            usuarioToSave.usuario = usuario;
            usuarioToSave.contrasenia = contrasenia;
            usuarioToSave.nombres = nombres;
            usuarioToSave.apellidos = apellidos;
            usuarioToSave.telefono = telefono;
            usuarioToSave.correo = correo;
            usuarioToSave.rol = rol;
            

            try {
                usuarioRepo.actualizarUsuario(usuarioToSave);
                JOptionPane.showMessageDialog(null, "Se actualizó exitosamente");
                mostrarUsuarios();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "No se pudo actualizar, intentelo de nuevo");
            }
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void tblUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUsuarioMouseClicked
        // TODO add your handling code here:
        int row = tblUsuario.getSelectedRow();
        if(row >= 0){
            btnUpdate.setEnabled(true);
            btnSave.setEnabled(false);
            String id = tblUsuario.getModel().getValueAt(row, 0).toString();
            idSelected = id;
            UsuarioRepositorio usuarioRepo = new UsuarioRepositorio();
            Usuario v = usuarioRepo.Get(Integer.parseInt(id));            
            inputUsuario.setText(v.usuario);
            inputContrasenia.setText(v.contrasenia);
            inputNombres.setText(v.nombres);
            inputApellidos.setText(v.apellidos  );
            inputTelefono.setText(v.telefono);
            inputCorreo.setText(v.correo);
        }
    }//GEN-LAST:event_tblUsuarioMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JTextField inputApellidos;
    private javax.swing.JTextField inputContrasenia;
    private javax.swing.JTextField inputCorreo;
    private javax.swing.JTextField inputNombres;
    private javax.swing.JComboBox<String> inputRol;
    private javax.swing.JTextField inputTelefono;
    private javax.swing.JTextField inputUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblUsuario;
    // End of variables declaration//GEN-END:variables
}
